#OpenTheDoor configuration
#Tue Jul 14 22:29:27 CEST 2026
savePackets=true
targetHost=
apkPath=C\:\\Users\\InfoWare31\\Desktop\\APK AVATAR FIGHT\\avatarfightreborn.apk
defaultHttpStatus=200
targetPort=80
mode=auto
maxPrintableBytes=4096
scanOutput=reports/apk-scan-report.md
port=8080
mockDir=mocks
host=0.0.0.0
defaultHttpContentType=application/json; charset\=UTF-8
logDir=logs
